feat: prompt for instance interface IP address (#6627)
TUI users now have the option to specify an IP address when configuring
an ethernet interface for an instance on a FNN VPC. The option is
offered per interface after the user specifies the VPC prefix.

```
nico:test-org/bffe764c-fdd4-4f42-a42e-05c3100e17f3> instance create
VPC: tui-test-fnn-vpc  Ready
Machine UI-GPU-0001  ui-demo-gpu-01
Instance name: test specify ip
Select an operating system? [y/N] y
Operating System: tui-test-os  Ready
VPC prefix for interface: tui-test-fnn-prefix-ready
IP address (optional; leave blank to auto-assign from an available IP in the VPC prefix): 192.0.2.11
Add another interface (have 1)? [y/N] n
INFO: cli --config /tmp/nicocli-os-tui-test-009b91a91.yaml instance create --data '{"interfaces":[{"ipAddress":"192.0.2.11","isPhysical":true,"vpcPrefixId":"88000000-0000-4000-8000-000000000202"}],"machineId":"ui-demo-gpu-01","name":"test specify ip","operatingSystemId":"084f1d37-d7a0-4d3f-ad85-acd3ac3f0992","vpcId":"88000000-0000-4000-8000-000000000002"}'
```

## Related issues
(https://github.com/dsx-ai-factory/infra-controller/issues/6599)

## Type of Change
- [x] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality
- [ ] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Breaking Changes
- [ ] **This PR contains breaking changes**

## Testing
- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes
Errors from the REST layer look like this:

```
nico:test-org/bffe764c-fdd4-4f42-a42e-05c3100e17f3> instance create
VPC: tui-test-fnn-vpc  Ready
Machine UI-GPU-0001  ui-demo-gpu-01
Instance name: test ip address
Select an operating system? [y/N] y
Operating System: tui-test-os  Ready
VPC prefix for interface: tui-test-fnn-prefix-ready
IP address (optional; leave blank to auto-assign from an available IP in the VPC prefix): 192.0.2.10
Add another interface (have 1)? [y/N] n
INFO: cli --config /tmp/nicocli-os-tui-test-009b91a91.yaml instance create --data '{"interfaces":[{"ipAddress":"192.0.2.10","isPhysical":true,"vpcPrefixId":"88000000-0000-4000-8000-000000000202"}],"machineId":"ui-demo-gpu-01","name":"test ip address","operatingSystemId":"084f1d37-d7a0-4d3f-ad85-acd3ac3f0992","vpcId":"88000000-0000-4000-8000-000000000002"}'
Error: creating instance: API error 400: Error validating Instance creation request data
Details: {"ipAddress":"ipAddress must have a final host bit of 1"}
```

---------

Signed-off-by: Leah Itagaki <litagaki@nvidia.com>